var files_dup =
[
    [ "09012020-Unv", "dir_25f28c5a0cd939be0bcf6f90e08fb69b.html", "dir_25f28c5a0cd939be0bcf6f90e08fb69b" ],
    [ "boundaryConditions", "dir_c6f8acc3b06ec6eb5eae6f38143d2c3d.html", "dir_c6f8acc3b06ec6eb5eae6f38143d2c3d" ],
    [ "parallelFunctions", "dir_5a84aec2f2011f477f5fce61335404d5.html", "dir_5a84aec2f2011f477f5fce61335404d5" ],
    [ "DGAuxUltilitiesLib.cpp", "_d_g_aux_ultilities_lib_8cpp.html", "_d_g_aux_ultilities_lib_8cpp" ],
    [ "DGAuxUltilitiesLib.h", "_d_g_aux_ultilities_lib_8h.html", "_d_g_aux_ultilities_lib_8h" ],
    [ "DGMessagesLib.cpp", "_d_g_messages_lib_8cpp.html", "_d_g_messages_lib_8cpp" ],
    [ "DGMessagesLib.h", "_d_g_messages_lib_8h.html", "_d_g_messages_lib_8h" ],
    [ "VarDeclaration.cpp", "_vardeclaration_8cpp.html", "_vardeclaration_8cpp" ],
    [ "VarDeclaration.h", "_var_declaration_8h.html", "_var_declaration_8h" ],
    [ "CommandCheck.cpp", "_command_check_8cpp.html", "_command_check_8cpp" ],
    [ "CommandCheck.h", "_command_check_8h.html", "_command_check_8h" ],
    [ "ConstDeclaration.cpp", "_const_declaration_8cpp.html", null ],
    [ "ConstDeclaration.h", "_const_declaration_8h.html", "_const_declaration_8h" ],
    [ "debuggingFuncs.cpp", "debugging_funcs_8cpp.html", null ],
    [ "debuggingFuncs.h", "debugging_funcs_8h.html", null ],
    [ "DG2D.cpp", "_d_g2_d_8cpp.html", "_d_g2_d_8cpp" ],
    [ "DGController.cpp", "_d_g_controller_8cpp.html", "_d_g_controller_8cpp" ],
    [ "DGController.h", "_d_g_controller_8h.html", "_d_g_controller_8h" ],
    [ "DGIOLib.cpp", "_d_g_i_o_lib_8cpp.html", "_d_g_i_o_lib_8cpp" ],
    [ "DGIOLib.h", "_d_g_i_o_lib_8h.html", "_d_g_i_o_lib_8h" ],
    [ "DGLimiterLib.cpp", "_d_g_limiter_lib_8cpp.html", "_d_g_limiter_lib_8cpp" ],
    [ "DGLimiterLib.h", "_d_g_limiter_lib_8h.html", "_d_g_limiter_lib_8h" ],
    [ "DGMath.cpp", "_d_g_math_8cpp.html", "_d_g_math_8cpp" ],
    [ "DGMath.h", "_d_g_math_8h.html", "_d_g_math_8h" ],
    [ "DGMeshReaderLib.cpp", "_d_g_mesh_reader_lib_8cpp.html", "_d_g_mesh_reader_lib_8cpp" ],
    [ "DGMeshReaderLib.h", "_d_g_mesh_reader_lib_8h.html", "_d_g_mesh_reader_lib_8h" ],
    [ "DGPostProcessLib.cpp", "_d_g_post_process_lib_8cpp.html", "_d_g_post_process_lib_8cpp" ],
    [ "DGPostProcessLib.h", "_d_g_post_process_lib_8h.html", "_d_g_post_process_lib_8h" ],
    [ "DGProcLib.cpp", "_d_g_proc_lib_8cpp.html", "_d_g_proc_lib_8cpp" ],
    [ "DGProcLib.h", "_d_g_proc_lib_8h.html", "_d_g_proc_lib_8h" ],
    [ "dynamicVarDeclaration.cpp", "dynamic_var_declaration_8cpp.html", "dynamic_var_declaration_8cpp" ],
    [ "dynamicVarDeclaration.h", "dynamic_var_declaration_8h.html", "dynamic_var_declaration_8h" ],
    [ "NonEquilibriumBCsLib.cpp", "_non_equilibrium_b_cs_lib_8cpp.html", "_non_equilibrium_b_cs_lib_8cpp" ],
    [ "NonEquilibriumBCsLib.h", "_non_equilibrium_b_cs_lib_8h.html", "_non_equilibrium_b_cs_lib_8h" ],
    [ "readResults.py", "read_results_8py.html", "read_results_8py" ]
];